### ISSUE TITLE
Remove the duplicate 'tracking ID'

### ISSUE THREAD

**Issue by pravj** [Sumith1896/Sumith1896.github.io#1]
Hi @Sumith1896,

Man, you have no idea how hard this was bugging me. Gotcha, finally. :smile:

As you are using the _modified-lanyon_ theme for Jekyll. _Mistakenly_ you forgot to replace my _tracking ID_ with yours, in the file [_includes/ga.html](https://github.com/Sumith1896/Sumith1896.github.io/blob/master/_includes/ga.html#L7).

_Ideally_, you need to create your own identifier, [here.](https://developers.google.com/analytics/devguides/collection/analyticsjs/?hl=en)

Happy Blogging. :octocat:

**Comment by sumith1896** [comment]
Hi @pravj 
Sorry about that :) I blindly took over your theme in a hurry, I'll update it ASAP.

Do you get notified(mails or so) and hence is it troubling you?

**Comment by pravj** [comment]
It's OK. Nothing wrong with using the theme, just update the ID.

Yeah, it was redirecting your traffic's details to my _Google Analytics_.
And it felt weird because my blog does not have a page with URI, _/SymPy-at-PyCon-India-2015/_.
So I googled and found you.

**Comment by sumith1896** [comment]
Removed your ID. Will add mine whenever I get time to make one :) 
Thanks @pravj

**Comment by pravj** [comment]
Cool :)
